### ISSUE TITLE
incorrect privacy api class

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-block_campaign_manager#2]
as your table includes a "userid" field you need to extend the privacy api to include export/delete functions for that data.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check tables for userid fields and ensure that they are covered by the privacy class.

More information on the privacy class is here:
https://moodledev.io/docs/apis/subsystems/privacy

not a blocker for plugins db approval.

**Comment by mattan-d** [comment]
A userid field is no longer relevant and has been removed from the plugin.
