### ISSUE TITLE
incorrect location for config settings

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-block_campaign_manager#3]
global $CFG  is for core config - plugins are supposed to use the get_config() style apis

eg:
https://github.com/mattan-d/moodle-block_campaign_manager/blob/master/settings.php#L34C50-L34C84

should not be:
admin_setting_configtext('block_campaign_manager_num_entries',
but instead:
admin_setting_configtext('block_campaign_manager\num_entries',

and then instead of using $CFG you use the get_config api.

this is typically a blocker for plugins db as it violates the frankenstyle naming rules:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle

**Comment by mattan-d** [comment]
Fixed.
